[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ssy-lang"
version = "1.1.0"
authors = [
  { name="SillyOdyssey" }
]
description = "A highly custom, lightweight programming tool built from scratch using Pydroid 3 and Python."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Interpreters",
]

[project.scripts]
ssy = "ssy.ssycore:main"
